In [1]:
import numpy as np

Creating an array with n dimension

In [6]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

finding the dimensions of the array

In [8]:
a = np.array([[1,2],[3,4]])
a.ndim

2

datatype of the ndarray

In [9]:
a.dtype

dtype('int32')

3D array

In [12]:
a = np.array([[[1, 2, 3],[4,5,6]],[[1, 2, 3],[4,5,6]],[[1, 2, 3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

np.ones()

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

np.zeros()

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

np.full((rows,columns),data)

In [15]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

np.shape

In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [29]:
a.shape = (3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a.resize(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a.sum(axis = 0)

array([12, 15, 18])

In [33]:
a.max()

9

In [34]:
a.min(axis = 0)

array([1, 2, 3])

In [35]:
a.min(axis = 1)

array([1, 4, 7])

In [36]:
a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a + a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [39]:
a * a2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

dot product

In [44]:
print(a)
print(a2)
print(a.dot(a2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [45]:
print(a[0,0])
print(a[0][0])
# both gives the same result

1
1
